import '../models/fc_question_model.dart';
import '../models/fc_rule_model.dart';

/// Forward Chaining Knowledge Base
/// Berisi semua pertanyaan dan rules untuk deteksi speech delay

class FCKnowledgeBase {
  /// Semua pertanyaan berdasarkan usia
  static List<FCQuestionModel> getAllQuestions() {
    return [
      // ============ UNIVERSAL (SEMUA USIA) ============
      ..._universalQuestions,

      // ============ 12 BULAN ============
      ..._age12Questions,

      // ============ 24 BULAN ============
      ..._age24Questions,

      // ============ 36 BULAN ============
      ..._age36Questions,

      // ============ 48 BULAN ============
      ..._age48Questions,

      // ============ 60 BULAN ============
      ..._age60Questions,
    ];
  }

  /// Universal questions (sama untuk semua usia) - 7 pertanyaan
  static final List<FCQuestionModel> _universalQuestions = [
    const FCQuestionModel(
      id: 'univ_001',
      question: 'Apakah ada riwayat keterlambatan bicara dalam keluarga?',
      options: ['Ya', 'Tidak', 'Tidak tahu'],
      key: 'family_history',
      minAge: 0,
      maxAge: 999,
      category: 'history',
      priority: 1,
      weight: 0.9,
    ),
    const FCQuestionModel(
      id: 'univ_002',
      question: 'Apakah anak pernah mengalami masalah pendengaran?',
      options: ['Ya', 'Tidak', 'Tidak yakin'],
      key: 'hearing_issues',
      minAge: 0,
      maxAge: 999,
      category: 'medical',
      priority: 1,
      weight: 1.5,
    ),
    const FCQuestionModel(
      id: 'univ_003',
      question: 'Apakah ada kekhawatiran khusus dari orang tua/guru tentang bicara anak?',
      options: ['Ya', 'Tidak yakin', 'Tidak'],
      key: 'parent_concern',
      minAge: 0,
      maxAge: 999,
      category: 'concern',
      priority: 1,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'univ_004',
      question: 'Apakah anak menatap saat dipanggil namanya?',
      options: ['Selalu', 'Kadang-kadang', 'Jarang', 'Tidak pernah'],
      key: 'eye_contact',
      minAge: 0,
      maxAge: 999,
      category: 'response',
      priority: 1,
      weight: 1.1,
    ),
    const FCQuestionModel(
      id: 'univ_005',
      question: 'Apakah anak menunjuk jari untuk menunjukkan interesse?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'pointing',
      minAge: 0,
      maxAge: 999,
      category: 'communication',
      priority: 2,
      weight: 0.8,
    ),
    const FCQuestionModel(
      id: 'univ_006',
      question: 'Apakah anak tersenyum saat diajak berinteraksi?',
      options: ['Sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'social_smile',
      minAge: 0,
      maxAge: 999,
      category: 'social',
      priority: 2,
      weight: 0.7,
    ),
    const FCQuestionModel(
      id: 'univ_007',
      question: 'Apakah anak menunjukkan benda atau mainan kepada orang tua?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'show_objects',
      minAge: 0,
      maxAge: 999,
      category: 'communication',
      priority: 2,
      weight: 0.8,
    ),
  ];

  /// Questions untuk 12 bulan - 8 pertanyaan khusus
  static final List<FCQuestionModel> _age12Questions = [
    const FCQuestionModel(
      id: 'age12_001',
      question: 'Apakah anak sudah mengucapkan kata pertama?',
      options: ['Ya', 'Belum', 'Tidak yakin'],
      key: 'first_word',
      minAge: 0,
      maxAge: 17,
      category: 'speech',
      priority: 1,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age12_002',
      question: 'Apakah anak meniru suara atau kata sederhana?',
      options: ['Sering', 'Kadang-kadang', 'Jarang', 'Tidak pernah'],
      key: 'imitate_sounds',
      minAge: 0,
      maxAge: 17,
      category: 'speech',
      priority: 1,
      weight: 1.1,
    ),
    const FCQuestionModel(
      id: 'age12_003',
      question: 'Berapa jumlah kata yang sudah bisa diucapkan anak?',
      options: ['0 kata', '1 kata', '2-3 kata', 'Lebih dari 3'],
      key: 'vocabulary_count',
      minAge: 0,
      maxAge: 17,
      category: 'vocabulary',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age12_004',
      question: 'Apakah anak merespons saat dipanggil namanya?',
      options: ['Selalu', 'Kadang-kadang', 'Jarang', 'Tidak pernah'],
      key: 'name_response',
      minAge: 0,
      maxAge: 17,
      category: 'response',
      priority: 1,
      weight: 1.2,
    ),
    const FCQuestionModel(
      id: 'age12_005',
      question: 'Apakah anak menggunakan gesture/gerakan untuk berkomunikasi?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'gesture_comm',
      minAge: 0,
      maxAge: 17,
      category: 'communication',
      priority: 2,
      weight: 0.9,
    ),
    const FCQuestionModel(
      id: 'age12_006',
      question: 'Apakah anak bisa memahami perintah sederhana?',
      options: ['Ya', 'Kadang-kadang', 'Belum'],
      key: 'understand_simple',
      minAge: 0,
      maxAge: 17,
      category: 'comprehension',
      priority: 2,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'age12_007',
      question: 'Apakah anak babbling (mengoceh)?',
      options: ['Sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'babbling',
      minAge: 0,
      maxAge: 17,
      category: 'speech',
      priority: 2,
      weight: 0.8,
    ),
    const FCQuestionModel(
      id: 'age12_008',
      question: 'Apakah anak menggunakan suara untuk menarik perhatian?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'attention_sounds',
      minAge: 0,
      maxAge: 17,
      category: 'communication',
      priority: 3,
      weight: 0.7,
    ),
  ];

  /// Questions untuk 24 bulan - 8 pertanyaan khusus
  static final List<FCQuestionModel> _age24Questions = [
    const FCQuestionModel(
      id: 'age24_001',
      question: 'Berapa jumlah kata yang sudah bisa diucapkan anak?',
      options: ['Kurang dari 10', '10-25 kata', '25-50 kata', 'Lebih dari 50'],
      key: 'vocabulary_count',
      minAge: 18,
      maxAge: 29,
      category: 'vocabulary',
      priority: 1,
      weight: 1.5,
    ),
    const FCQuestionModel(
      id: 'age24_002',
      question: 'Apakah anak bisa membuat kalimat 2 kata?',
      options: ['Ya', 'Kadang-kadang', 'Belum'],
      key: 'two_word_phrase',
      minAge: 18,
      maxAge: 29,
      category: 'speech',
      priority: 1,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age24_003',
      question: 'Apakah orang lain bisa memahami ucapan anak Anda?',
      options: ['Selalu', 'Kadang-kadang', 'Jarang', 'Tidak pernah'],
      key: 'speech_clarity',
      minAge: 18,
      maxAge: 29,
      category: 'articulation',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age24_004',
      question: 'Apakah anak bertanya "apa itu"?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'asking_what',
      minAge: 18,
      maxAge: 29,
      category: 'communication',
      priority: 2,
      weight: 0.9,
    ),
    const FCQuestionModel(
      id: 'age24_005',
      question: 'Apakah anak bisa mengikuti perintah 2 langkah?',
      options: ['Ya', 'Kadang-kadang', 'Belum'],
      key: 'follow_commands_two',
      minAge: 18,
      maxAge: 29,
      category: 'comprehension',
      priority: 2,
      weight: 1.1,
    ),
    const FCQuestionModel(
      id: 'age24_006',
      question: 'Apakah anak menunjuk bagian tubuh saat diminta?',
      options: ['Ya, semua', 'Sebagian', 'Sedikit', 'Tidak'],
      key: 'point_body_parts',
      minAge: 18,
      maxAge: 29,
      category: 'comprehension',
      priority: 2,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'age24_007',
      question: 'Apakah anak menggunakan kata "saya" atau "aku"?',
      options: ['Ya, sering', 'Kadang-kadang', 'Belum'],
      key: 'uses_i_me',
      minAge: 18,
      maxAge: 29,
      category: 'speech',
      priority: 3,
      weight: 0.8,
    ),
    const FCQuestionModel(
      id: 'age24_008',
      question: 'Apakah anak menikmati dibacakan cerita?',
      options: ['Sangat', 'Ya', 'Kadang-kadang', 'Tidak'],
      key: 'enjoy_stories',
      minAge: 18,
      maxAge: 29,
      category: 'social',
      priority: 3,
      weight: 0.7,
    ),
  ];

  /// Questions untuk 36 bulan - 8 pertanyaan khusus
  static final List<FCQuestionModel> _age36Questions = [
    const FCQuestionModel(
      id: 'age36_001',
      question: 'Berapa jumlah kata yang sudah bisa diucapkan anak?',
      options: ['Kurang dari 50', '50-200 kata', '200-500 kata', 'Lebih dari 500'],
      key: 'vocabulary_count',
      minAge: 30,
      maxAge: 41,
      category: 'vocabulary',
      priority: 1,
      weight: 1.5,
    ),
    const FCQuestionModel(
      id: 'age36_002',
      question: 'Apakah anak bisa membuat kalimat 3-4 kata?',
      options: ['Ya, dengan baik', 'Ya, kadang salah', 'Masih belajar', 'Belum'],
      key: 'three_word_sentence',
      minAge: 30,
      maxAge: 41,
      category: 'speech',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age36_003',
      question: 'Apakah orang lain bisa memahami ucapan anak Anda?',
      options: ['Selalu', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'speech_clarity',
      minAge: 30,
      maxAge: 41,
      category: 'articulation',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age36_004',
      question: 'Apakah anak bisa menceritakan pengalaman hariannya?',
      options: ['Ya, detail', 'Ya, singkat', 'Kadang-kadang', 'Belum'],
      key: 'narrative_skill',
      minAge: 30,
      maxAge: 41,
      category: 'language',
      priority: 2,
      weight: 1.2,
    ),
    const FCQuestionModel(
      id: 'age36_005',
      question: 'Apakah anak bertanya menggunakan kata "mengapa"?',
      options: ['Ya, sering', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'asking_why',
      minAge: 30,
      maxAge: 41,
      category: 'communication',
      priority: 2,
      weight: 0.9,
    ),
    const FCQuestionModel(
      id: 'age36_006',
      question: 'Apakah anak bisa menyebut warna dasar?',
      options: ['Ya, semua', 'Sebagian', 'Sedikit', 'Belum'],
      key: 'color_recognition',
      minAge: 30,
      maxAge: 41,
      category: 'vocabulary',
      priority: 2,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'age36_007',
      question: 'Apakah anak kesulitan mengucapkan huruf tertentu?',
      options: ['Tidak ada', 'Sedikit', 'Banyak', 'Tidak yakin'],
      key: 'articulation_difficulty',
      minAge: 30,
      maxAge: 41,
      category: 'articulation',
      priority: 2,
      weight: 1.2,
    ),
    const FCQuestionModel(
      id: 'age36_008',
      question: 'Apakah anak bisa bermain peran (pretend play)?',
      options: ['Ya', 'Kadang-kadang', 'Jarang', 'Tidak'],
      key: 'pretend_play',
      minAge: 30,
      maxAge: 41,
      category: 'social',
      priority: 3,
      weight: 0.8,
    ),
  ];

  /// Questions untuk 48 bulan - 8 pertanyaan khusus
  static final List<FCQuestionModel> _age48Questions = [
    const FCQuestionModel(
      id: 'age48_001',
      question: 'Berapa jumlah kata yang sudah bisa diucapkan anak?',
      options: ['Kurang dari 200', '200-500 kata', '500-1000 kata', 'Lebih dari 1000'],
      key: 'vocabulary_count',
      minAge: 42,
      maxAge: 53,
      category: 'vocabulary',
      priority: 1,
      weight: 1.5,
    ),
    const FCQuestionModel(
      id: 'age48_002',
      question: 'Apakah anak bisa menceritakan cerita dengan alur yang jelas?',
      options: ['Ya, baik', 'Ya, sederhana', 'Kadang-kadang', 'Belum'],
      key: 'storytelling',
      minAge: 42,
      maxAge: 53,
      category: 'language',
      priority: 1,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age48_003',
      question: 'Apakah orang lain bisa memahami hampir semua ucapan anak?',
      options: ['Ya', 'Sebagian besar', 'Sebagian', 'Sulit dipahami'],
      key: 'speech_clarity',
      minAge: 42,
      maxAge: 53,
      category: 'articulation',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age48_004',
      question: 'Apakah anak bisa menjawab pertanyaan "siapa", "apa", "di mana"?',
      options: ['Ya, semua', 'Sebagian besar', 'Sebagian', 'Belum'],
      key: 'answer_questions',
      minAge: 42,
      maxAge: 53,
      category: 'comprehension',
      priority: 2,
      weight: 1.2,
    ),
    const FCQuestionModel(
      id: 'age48_005',
      question: 'Apakah anak kesulitan mengucapkan huruf R, S, L?',
      options: ['Tidak', 'Sedikit', 'Banyak', 'Sangat banyak'],
      key: 'letter_difficulty',
      minAge: 42,
      maxAge: 53,
      category: 'articulation',
      priority: 2,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age48_006',
      question: 'Apakah anak bisa bernyanyi lagu sederhana?',
      options: ['Ya', 'Sebagian', 'Sedikit', 'Tidak'],
      key: 'sing_songs',
      minAge: 42,
      maxAge: 53,
      category: 'speech',
      priority: 3,
      weight: 0.8,
    ),
    const FCQuestionModel(
      id: 'age48_007',
      question: 'Apakah anak bisa bermain dan berbagi dengan anak lain?',
      options: ['Ya, baik', 'Ya, kadang konflik', 'Sulit', 'Prefer sendiri'],
      key: 'social_play',
      minAge: 42,
      maxAge: 53,
      category: 'social',
      priority: 2,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'age48_008',
      question: 'Apakah anak bisa memahami konsep jumlah (lebih banyak/lebih sedikit)?',
      options: ['Ya', 'Kadang-kadang', 'Belum'],
      key: 'quantity_concept',
      minAge: 42,
      maxAge: 53,
      category: 'comprehension',
      priority: 3,
      weight: 0.9,
    ),
  ];

  /// Questions untuk 60 bulan - 8 pertanyaan khusus
  static final List<FCQuestionModel> _age60Questions = [
    const FCQuestionModel(
      id: 'age60_001',
      question: 'Berapa jumlah kata yang sudah bisa diucapkan anak?',
      options: ['Kurang dari 500', '500-1500 kata', '1500-2500 kata', 'Lebih dari 2500'],
      key: 'vocabulary_count',
      minAge: 54,
      maxAge: 72,
      category: 'vocabulary',
      priority: 1,
      weight: 1.5,
    ),
    const FCQuestionModel(
      id: 'age60_002',
      question: 'Apakah anak bisa bercerita dengan awal, tengah, akhir yang jelas?',
      options: ['Ya', 'Ya, sederhana', 'Kadang-kadang', 'Belum'],
      key: 'story_structure',
      minAge: 54,
      maxAge: 72,
      category: 'language',
      priority: 1,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age60_003',
      question: 'Apakah orang lain bisa memahami hampir semua ucapan anak?',
      options: ['Ya, semua', 'Ya, hampir semua', 'Sebagian', 'Sulit'],
      key: 'speech_clarity',
      minAge: 54,
      maxAge: 72,
      category: 'articulation',
      priority: 1,
      weight: 1.4,
    ),
    const FCQuestionModel(
      id: 'age60_004',
      question: 'Apakah anak kesulitan mengucapkan huruf tertentu?',
      options: ['Tidak ada', 'R/S/L sedikit', 'Banyak huruf', 'Sangat banyak'],
      key: 'articulation_difficulty',
      minAge: 54,
      maxAge: 72,
      category: 'articulation',
      priority: 1,
      weight: 1.3,
    ),
    const FCQuestionModel(
      id: 'age60_005',
      question: 'Apakah anak bisa mengikuti aturan permainan kelompok?',
      options: ['Ya, baik', 'Ya, kadang perlu bantuan', 'Sulit', 'Belum pernah'],
      key: 'follow_rules',
      minAge: 54,
      maxAge: 72,
      category: 'social',
      priority: 2,
      weight: 1.1,
    ),
    const FCQuestionModel(
      id: 'age60_006',
      question: 'Apakah anak bisa menjawab pertanyaan kompleks?',
      options: ['Ya, semua', 'Ya, sebagian', 'Sedikit', 'Belum'],
      key: 'complex_questions',
      minAge: 54,
      maxAge: 72,
      category: 'comprehension',
      priority: 2,
      weight: 1.2,
    ),
    const FCQuestionModel(
      id: 'age60_007',
      question: 'Apakah speech anak lebih jelas dari anak seusianya?',
      options: ['Ya, lebih jelas', 'Serupa', 'Kurang jelas', 'Jauh berbeda'],
      key: 'speech_comparison',
      minAge: 54,
      maxAge: 72,
      category: 'articulation',
      priority: 2,
      weight: 1.0,
    ),
    const FCQuestionModel(
      id: 'age60_008',
      question: 'Apakah anak bisa mengekspresikan perasaan dengan kata-kata?',
      options: ['Ya, dengan baik', 'Ya', 'Kadang-kadang', 'Belum'],
      key: 'express_feelings',
      minAge: 54,
      maxAge: 72,
      category: 'communication',
      priority: 3,
      weight: 0.9,
    ),
  ];

  /// Get questions untuk usia tertentu
  static List<FCQuestionModel> getQuestionsForAge(int ageInMonths) {
    final allQuestions = getAllQuestions();
    return allQuestions
        .where((q) => q.isRelevantForAge(ageInMonths))
        .toList()
      ..sort((a, b) => a.priority.compareTo(b.priority));
  }

  /// Get categories untuk usia tertentu
  static List<String> getCategoriesForAge(int ageInMonths) {
    final questions = getQuestionsForAge(ageInMonths);
    return questions.map((q) => q.category).toSet().toList();
  }
}
