import '../models/fc_rule_model.dart';

/// Forward Chaining Rules Knowledge Base
/// Berisi semua rules untuk deteksi speech delay berdasarkan WHO/DDST milestones

class FCRules {
  /// Get all rules
  static List<FCRuleModel> getAllRules() {
    return [
      ..._infantRules,
      ..._toddlerRules,
      ..._preschoolRules,
      ..._universalRules,
    ];
  }

  // ============ INFANT RULES (12-18 BULAN) ============
  static final List<FCRuleModel> _infantRules = [
    const FCRuleModel(
      id: 'infant_r020',
      name: 'first_word - first_word_baik',
      antecedents: {
        'first_word': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'first_word_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Perkembangan kata pertama menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'infant_r021',
      name: 'first_word - first_word_cukup',
      antecedents: {
        'first_word': ['Tidak yakin'],
      },
      operator: 'AND',
      conclusion: 'first_word_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Perkembangan kata pertama dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r022',
      name: 'first_word - first_word_kurang',
      antecedents: {
        'first_word': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'first_word_kurang',
      confidence: 0.9,
      minAge: 10,
      maxAge: 18,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Perkembangan kata pertama terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'infant_r023',
      name: 'imitate_sounds - imitate_sounds_baik',
      antecedents: {
        'imitate_sounds': ['Sering'],
      },
      operator: 'AND',
      conclusion: 'imitate_sounds_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan meniru suara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r024',
      name: 'imitate_sounds - imitate_sounds_cukup',
      antecedents: {
        'imitate_sounds': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'imitate_sounds_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan meniru suara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r025',
      name: 'imitate_sounds - imitate_sounds_kurang',
      antecedents: {
        'imitate_sounds': ['Jarang', 'Tidak pernah'],
      },
      operator: 'AND',
      conclusion: 'imitate_sounds_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan meniru suara kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'infant_r026',
      name: 'vocabulary_count - vocabulary_count_12_baik',
      antecedents: {
        'vocabulary_count': ['2-3 kata', 'Lebih dari 3'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_12_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r027',
      name: 'vocabulary_count - vocabulary_count_12_cukup',
      antecedents: {
        'vocabulary_count': ['1 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_12_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r028',
      name: 'vocabulary_count - vocabulary_count_12_kurang',
      antecedents: {
        'vocabulary_count': ['0 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_12_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'vocabulary',
      severityImpact: 2,
      recommendation: 'Kemampuan jumlah kosa kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'infant_r029',
      name: 'name_response - name_response_baik',
      antecedents: {
        'name_response': ['Selalu'],
      },
      operator: 'AND',
      conclusion: 'name_response_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'response',
      severityImpact: 0,
      recommendation: 'Kemampuan respon terhadap panggilan nama sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r030',
      name: 'name_response - name_response_cukup',
      antecedents: {
        'name_response': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'name_response_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'response',
      severityImpact: 0,
      recommendation: 'Kemampuan respon terhadap panggilan nama cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r031',
      name: 'name_response - name_response_kurang',
      antecedents: {
        'name_response': ['Jarang', 'Tidak pernah'],
      },
      operator: 'AND',
      conclusion: 'name_response_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'response',
      severityImpact: 2,
      recommendation: 'Kemampuan respon terhadap panggilan nama kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'infant_r032',
      name: 'gesture_comm - gesture_comm_baik',
      antecedents: {
        'gesture_comm': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'gesture_comm_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan komunikasi dengan gerakan sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r033',
      name: 'gesture_comm - gesture_comm_cukup',
      antecedents: {
        'gesture_comm': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'gesture_comm_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan komunikasi dengan gerakan cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r034',
      name: 'gesture_comm - gesture_comm_kurang',
      antecedents: {
        'gesture_comm': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'gesture_comm_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan komunikasi dengan gerakan kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'infant_r035',
      name: 'understand_simple - understand_simple_baik',
      antecedents: {
        'understand_simple': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'understand_simple_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan pemahaman perintah sederhana menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'infant_r036',
      name: 'understand_simple - understand_simple_cukup',
      antecedents: {
        'understand_simple': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'understand_simple_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan pemahaman perintah sederhana dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r037',
      name: 'understand_simple - understand_simple_kurang',
      antecedents: {
        'understand_simple': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'understand_simple_kurang',
      confidence: 0.9,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Perkembangan pemahaman perintah sederhana terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'infant_r038',
      name: 'babbling - babbling_baik',
      antecedents: {
        'babbling': ['Sering'],
      },
      operator: 'AND',
      conclusion: 'babbling_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengoceh sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r039',
      name: 'babbling - babbling_cukup',
      antecedents: {
        'babbling': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'babbling_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengoceh cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r040',
      name: 'babbling - babbling_kurang',
      antecedents: {
        'babbling': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'babbling_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan mengoceh kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'infant_r041',
      name: 'attention_sounds - attention_sounds_baik',
      antecedents: {
        'attention_sounds': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'attention_sounds_baik',
      confidence: 0.8,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan perhatian pada suara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'infant_r042',
      name: 'attention_sounds - attention_sounds_cukup',
      antecedents: {
        'attention_sounds': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'attention_sounds_cukup',
      confidence: 0.7,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan perhatian pada suara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'infant_r043',
      name: 'attention_sounds - attention_sounds_kurang',
      antecedents: {
        'attention_sounds': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'attention_sounds_kurang',
      confidence: 0.85,
      minAge: 10,
      maxAge: 18,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan perhatian pada suara kurang, perlu perhatian khusus',
    ),
  ];

  // ============ TODDLER RULES (18-36 BULAN) ============
  static final List<FCRuleModel> _toddlerRules = [
    const FCRuleModel(
      id: 'toddler_r044',
      name: 'vocabulary_count - vocabulary_count_24_baik',
      antecedents: {
        'vocabulary_count': ['25-50 kata', 'Lebih dari 50'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_24_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'toddler_r045',
      name: 'vocabulary_count - vocabulary_count_24_cukup',
      antecedents: {
        'vocabulary_count': ['10-25 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_24_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r046',
      name: 'vocabulary_count - vocabulary_count_24_kurang',
      antecedents: {
        'vocabulary_count': ['Kurang dari 10'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_24_kurang',
      confidence: 0.85,
      minAge: 18,
      maxAge: 32,
      category: 'vocabulary',
      severityImpact: 2,
      recommendation: 'Kemampuan jumlah kosa kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'toddler_r047',
      name: 'two_word_phrase - two_word_phrase_baik',
      antecedents: {
        'two_word_phrase': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'two_word_phrase_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Perkembangan penggunaan frasa dua kata menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'toddler_r048',
      name: 'two_word_phrase - two_word_phrase_cukup',
      antecedents: {
        'two_word_phrase': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'two_word_phrase_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Perkembangan penggunaan frasa dua kata dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r049',
      name: 'two_word_phrase - two_word_phrase_kurang',
      antecedents: {
        'two_word_phrase': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'two_word_phrase_kurang',
      confidence: 0.9,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Perkembangan penggunaan frasa dua kata terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'toddler_r050',
      name: 'speech_clarity - speech_clarity_24_baik',
      antecedents: {
        'speech_clarity': ['Selalu'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_24_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'toddler_r051',
      name: 'speech_clarity - speech_clarity_24_cukup',
      antecedents: {
        'speech_clarity': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_24_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r052',
      name: 'speech_clarity - speech_clarity_24_kurang',
      antecedents: {
        'speech_clarity': ['Jarang', 'Tidak pernah'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_24_kurang',
      confidence: 0.85,
      minAge: 18,
      maxAge: 32,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan kejelasan bicara kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'toddler_r053',
      name: 'asking_what - asking_what_baik',
      antecedents: {
        'asking_what': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'asking_what_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan bertanya menggunakan kata \'apa\' sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'toddler_r054',
      name: 'asking_what - asking_what_cukup',
      antecedents: {
        'asking_what': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'asking_what_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan bertanya menggunakan kata \'apa\' cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r055',
      name: 'asking_what - asking_what_kurang',
      antecedents: {
        'asking_what': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'asking_what_kurang',
      confidence: 0.85,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan bertanya menggunakan kata \'apa\' kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'toddler_r056',
      name: 'follow_commands_two - follow_commands_two_baik',
      antecedents: {
        'follow_commands_two': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'follow_commands_two_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan mengikuti dua perintah sekaligus menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'toddler_r057',
      name: 'follow_commands_two - follow_commands_two_cukup',
      antecedents: {
        'follow_commands_two': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'follow_commands_two_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan mengikuti dua perintah sekaligus dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r058',
      name: 'follow_commands_two - follow_commands_two_kurang',
      antecedents: {
        'follow_commands_two': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'follow_commands_two_kurang',
      confidence: 0.9,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Perkembangan mengikuti dua perintah sekaligus terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'toddler_r059',
      name: 'point_body_parts - point_body_parts_baik',
      antecedents: {
        'point_body_parts': ['Ya, semua'],
      },
      operator: 'AND',
      conclusion: 'point_body_parts_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menunjuk bagian tubuh sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'toddler_r060',
      name: 'point_body_parts - point_body_parts_cukup',
      antecedents: {
        'point_body_parts': ['Sebagian'],
      },
      operator: 'AND',
      conclusion: 'point_body_parts_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menunjuk bagian tubuh cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r061',
      name: 'point_body_parts - point_body_parts_kurang',
      antecedents: {
        'point_body_parts': ['Sedikit', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'point_body_parts_kurang',
      confidence: 0.85,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan menunjuk bagian tubuh kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'toddler_r062',
      name: 'uses_i_me - uses_i_me_baik',
      antecedents: {
        'uses_i_me': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'uses_i_me_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan penggunaan kata \'saya\' atau \'aku\' menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'toddler_r063',
      name: 'uses_i_me - uses_i_me_cukup',
      antecedents: {
        'uses_i_me': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'uses_i_me_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan penggunaan kata \'saya\' atau \'aku\' dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r064',
      name: 'uses_i_me - uses_i_me_kurang',
      antecedents: {
        'uses_i_me': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'uses_i_me_kurang',
      confidence: 0.9,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Perkembangan penggunaan kata \'saya\' atau \'aku\' terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'toddler_r065',
      name: 'enjoy_stories - enjoy_stories_baik',
      antecedents: {
        'enjoy_stories': ['Sangat'],
      },
      operator: 'AND',
      conclusion: 'enjoy_stories_baik',
      confidence: 0.8,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan ketertarikan pada cerita sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'toddler_r066',
      name: 'enjoy_stories - enjoy_stories_cukup',
      antecedents: {
        'enjoy_stories': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'enjoy_stories_cukup',
      confidence: 0.7,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan ketertarikan pada cerita cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'toddler_r067',
      name: 'enjoy_stories - enjoy_stories_kurang',
      antecedents: {
        'enjoy_stories': ['Kadang-kadang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'enjoy_stories_kurang',
      confidence: 0.85,
      minAge: 18,
      maxAge: 32,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan ketertarikan pada cerita kurang, perlu perhatian khusus',
    ),
  ];

  // ============ PRESCHOOL RULES (36-60 BULAN) ============
  static final List<FCRuleModel> _preschoolRules = [
    const FCRuleModel(
      id: 'preschool_r068',
      name: 'vocabulary_count - vocabulary_count_36_baik',
      antecedents: {
        'vocabulary_count': ['200-500 kata', 'Lebih dari 500'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_36_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r069',
      name: 'vocabulary_count - vocabulary_count_36_cukup',
      antecedents: {
        'vocabulary_count': ['50-200 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_36_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r070',
      name: 'vocabulary_count - vocabulary_count_36_kurang',
      antecedents: {
        'vocabulary_count': ['Kurang dari 50'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_36_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'vocabulary',
      severityImpact: 2,
      recommendation: 'Kemampuan jumlah kosa kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r071',
      name: 'three_word_sentence - three_word_sentence_baik',
      antecedents: {
        'three_word_sentence': ['Ya, dengan baik'],
      },
      operator: 'AND',
      conclusion: 'three_word_sentence_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan penggunaan kalimat tiga kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r072',
      name: 'three_word_sentence - three_word_sentence_cukup',
      antecedents: {
        'three_word_sentence': ['Ya, kadang salah'],
      },
      operator: 'AND',
      conclusion: 'three_word_sentence_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan penggunaan kalimat tiga kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r073',
      name: 'three_word_sentence - three_word_sentence_kurang',
      antecedents: {
        'three_word_sentence': ['Masih belajar', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'three_word_sentence_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan penggunaan kalimat tiga kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r074',
      name: 'speech_clarity - speech_clarity_36_baik',
      antecedents: {
        'speech_clarity': ['Selalu'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_36_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r075',
      name: 'speech_clarity - speech_clarity_36_cukup',
      antecedents: {
        'speech_clarity': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_36_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r076',
      name: 'speech_clarity - speech_clarity_36_kurang',
      antecedents: {
        'speech_clarity': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_36_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan kejelasan bicara kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r077',
      name: 'narrative_skill - narrative_skill_baik',
      antecedents: {
        'narrative_skill': ['Ya, detail'],
      },
      operator: 'AND',
      conclusion: 'narrative_skill_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan narrative_skill sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r078',
      name: 'narrative_skill - narrative_skill_cukup',
      antecedents: {
        'narrative_skill': ['Ya, singkat'],
      },
      operator: 'AND',
      conclusion: 'narrative_skill_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan narrative_skill cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r079',
      name: 'narrative_skill - narrative_skill_kurang',
      antecedents: {
        'narrative_skill': ['Kadang-kadang', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'narrative_skill_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan narrative_skill kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r080',
      name: 'asking_why - asking_why_baik',
      antecedents: {
        'asking_why': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'asking_why_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan asking_why sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r081',
      name: 'asking_why - asking_why_cukup',
      antecedents: {
        'asking_why': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'asking_why_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan asking_why cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r082',
      name: 'asking_why - asking_why_kurang',
      antecedents: {
        'asking_why': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'asking_why_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan asking_why kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r083',
      name: 'color_recognition - color_recognition_baik',
      antecedents: {
        'color_recognition': ['Ya, semua'],
      },
      operator: 'AND',
      conclusion: 'color_recognition_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan color_recognition sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r084',
      name: 'color_recognition - color_recognition_cukup',
      antecedents: {
        'color_recognition': ['Sebagian'],
      },
      operator: 'AND',
      conclusion: 'color_recognition_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan color_recognition cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r085',
      name: 'color_recognition - color_recognition_kurang',
      antecedents: {
        'color_recognition': ['Sedikit', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'color_recognition_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan color_recognition kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r086',
      name: 'articulation_difficulty - articulation_difficulty_36_baik',
      antecedents: {
        'articulation_difficulty': ['Tidak ada'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_36_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan articulation_difficulty_36 sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r087',
      name: 'articulation_difficulty - articulation_difficulty_36_cukup',
      antecedents: {
        'articulation_difficulty': ['Sedikit'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_36_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan articulation_difficulty_36 cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r088',
      name: 'articulation_difficulty - articulation_difficulty_36_kurang',
      antecedents: {
        'articulation_difficulty': ['Banyak', 'Tidak yakin'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_36_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan articulation_difficulty_36 kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r089',
      name: 'pretend_play - pretend_play_baik',
      antecedents: {
        'pretend_play': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'pretend_play_baik',
      confidence: 0.8,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan pretend_play sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r090',
      name: 'pretend_play - pretend_play_cukup',
      antecedents: {
        'pretend_play': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'pretend_play_cukup',
      confidence: 0.7,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan pretend_play cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r091',
      name: 'pretend_play - pretend_play_kurang',
      antecedents: {
        'pretend_play': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'pretend_play_kurang',
      confidence: 0.85,
      minAge: 32,
      maxAge: 44,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan pretend_play kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r092',
      name: 'vocabulary_count - vocabulary_count_48_baik',
      antecedents: {
        'vocabulary_count': ['500-1000 kata', 'Lebih dari 1000'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_48_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r093',
      name: 'vocabulary_count - vocabulary_count_48_cukup',
      antecedents: {
        'vocabulary_count': ['200-500 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_48_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan jumlah kosa kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r094',
      name: 'vocabulary_count - vocabulary_count_48_kurang',
      antecedents: {
        'vocabulary_count': ['Kurang dari 200'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_48_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'vocabulary',
      severityImpact: 2,
      recommendation: 'Kemampuan jumlah kosa kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r095',
      name: 'storytelling - storytelling_baik',
      antecedents: {
        'storytelling': ['Ya, baik'],
      },
      operator: 'AND',
      conclusion: 'storytelling_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan storytelling sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r096',
      name: 'storytelling - storytelling_cukup',
      antecedents: {
        'storytelling': ['Ya, sederhana'],
      },
      operator: 'AND',
      conclusion: 'storytelling_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan storytelling cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r097',
      name: 'storytelling - storytelling_kurang',
      antecedents: {
        'storytelling': ['Kadang-kadang', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'storytelling_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan storytelling kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r098',
      name: 'speech_clarity - speech_clarity_48_baik',
      antecedents: {
        'speech_clarity': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_48_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r099',
      name: 'speech_clarity - speech_clarity_48_cukup',
      antecedents: {
        'speech_clarity': ['Sebagian besar'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_48_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r100',
      name: 'speech_clarity - speech_clarity_48_kurang',
      antecedents: {
        'speech_clarity': ['Sebagian', 'Sulit dipahami'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_48_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan kejelasan bicara kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r101',
      name: 'answer_questions - answer_questions_48_baik',
      antecedents: {
        'answer_questions': ['Ya, semua'],
      },
      operator: 'AND',
      conclusion: 'answer_questions_48_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan answer_questions_48 sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r102',
      name: 'answer_questions - answer_questions_48_cukup',
      antecedents: {
        'answer_questions': ['Sebagian besar'],
      },
      operator: 'AND',
      conclusion: 'answer_questions_48_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan answer_questions_48 cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r103',
      name: 'answer_questions - answer_questions_48_kurang',
      antecedents: {
        'answer_questions': ['Sebagian', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'answer_questions_48_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan answer_questions_48 kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r104',
      name: 'letter_difficulty - letter_difficulty_baik',
      antecedents: {
        'letter_difficulty': ['Tidak'],
      },
      operator: 'AND',
      conclusion: 'letter_difficulty_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan letter_difficulty sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r105',
      name: 'letter_difficulty - letter_difficulty_cukup',
      antecedents: {
        'letter_difficulty': ['Sedikit'],
      },
      operator: 'AND',
      conclusion: 'letter_difficulty_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan letter_difficulty cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r106',
      name: 'letter_difficulty - letter_difficulty_kurang',
      antecedents: {
        'letter_difficulty': ['Banyak', 'Sangat banyak'],
      },
      operator: 'AND',
      conclusion: 'letter_difficulty_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan letter_difficulty kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r107',
      name: 'sing_songs - sing_songs_baik',
      antecedents: {
        'sing_songs': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'sing_songs_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan sing_songs sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r108',
      name: 'sing_songs - sing_songs_cukup',
      antecedents: {
        'sing_songs': ['Sebagian'],
      },
      operator: 'AND',
      conclusion: 'sing_songs_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan sing_songs cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r109',
      name: 'sing_songs - sing_songs_kurang',
      antecedents: {
        'sing_songs': ['Sedikit', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'sing_songs_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan sing_songs kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r110',
      name: 'social_play - social_play_baik',
      antecedents: {
        'social_play': ['Ya, baik'],
      },
      operator: 'AND',
      conclusion: 'social_play_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan social_play sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r111',
      name: 'social_play - social_play_cukup',
      antecedents: {
        'social_play': ['Ya, kadang konflik'],
      },
      operator: 'AND',
      conclusion: 'social_play_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan social_play cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r112',
      name: 'social_play - social_play_kurang',
      antecedents: {
        'social_play': ['Sulit', 'Prefer sendiri'],
      },
      operator: 'AND',
      conclusion: 'social_play_kurang',
      confidence: 0.85,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan social_play kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r113',
      name: 'quantity_concept - quantity_concept_baik',
      antecedents: {
        'quantity_concept': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'quantity_concept_baik',
      confidence: 0.8,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan quantity_concept menunjukkan hasil positif',
    ),
    const FCRuleModel(
      id: 'preschool_r114',
      name: 'quantity_concept - quantity_concept_cukup',
      antecedents: {
        'quantity_concept': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'quantity_concept_cukup',
      confidence: 0.7,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Perkembangan quantity_concept dalam tahap belajar, berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r115',
      name: 'quantity_concept - quantity_concept_kurang',
      antecedents: {
        'quantity_concept': ['Belum'],
      },
      operator: 'AND',
      conclusion: 'quantity_concept_kurang',
      confidence: 0.9,
      minAge: 44,
      maxAge: 56,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Perkembangan quantity_concept terlambat, segera konsultasikan',
    ),
    const FCRuleModel(
      id: 'preschool_r116',
      name: 'vocabulary_count - vocabulary_count_60_baik',
      antecedents: {
        'vocabulary_count': ['1500-2500 kata', 'Lebih dari 2500'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_60_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan kosa kata sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r117',
      name: 'vocabulary_count - vocabulary_count_60_cukup',
      antecedents: {
        'vocabulary_count': ['500-1500 kata'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_60_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'vocabulary',
      severityImpact: 0,
      recommendation: 'Kemampuan kosa kata cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r118',
      name: 'vocabulary_count - vocabulary_count_60_kurang',
      antecedents: {
        'vocabulary_count': ['Kurang dari 500'],
      },
      operator: 'AND',
      conclusion: 'vocabulary_count_60_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'vocabulary',
      severityImpact: 2,
      recommendation: 'Kemampuan kosa kata kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r119',
      name: 'story_structure - story_structure_baik',
      antecedents: {
        'story_structure': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'story_structure_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menyusun struktur cerita sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r120',
      name: 'story_structure - story_structure_cukup',
      antecedents: {
        'story_structure': ['Ya, sederhana'],
      },
      operator: 'AND',
      conclusion: 'story_structure_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menyusun struktur cerita cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r121',
      name: 'story_structure - story_structure_kurang',
      antecedents: {
        'story_structure': ['Kadang-kadang', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'story_structure_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan menyusun struktur cerita kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r122',
      name: 'speech_clarity - speech_clarity_60_baik',
      antecedents: {
        'speech_clarity': ['Ya, semua'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_60_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r123',
      name: 'speech_clarity - speech_clarity_60_cukup',
      antecedents: {
        'speech_clarity': ['Ya, hampir semua'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_60_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kejelasan bicara cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r124',
      name: 'speech_clarity - speech_clarity_60_kurang',
      antecedents: {
        'speech_clarity': ['Sebagian', 'Sulit'],
      },
      operator: 'AND',
      conclusion: 'speech_clarity_60_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan kejelasan bicara kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r125',
      name: 'articulation_difficulty - articulation_difficulty_60_baik',
      antecedents: {
        'articulation_difficulty': ['Tidak ada'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_60_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan artikulasi sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r126',
      name: 'articulation_difficulty - articulation_difficulty_60_cukup',
      antecedents: {
        'articulation_difficulty': ['R/S/L sedikit'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_60_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan artikulasi cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r127',
      name: 'articulation_difficulty - articulation_difficulty_60_kurang',
      antecedents: {
        'articulation_difficulty': ['Banyak huruf', 'Sangat banyak'],
      },
      operator: 'AND',
      conclusion: 'articulation_difficulty_60_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan artikulasi kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r128',
      name: 'follow_rules - follow_rules_baik',
      antecedents: {
        'follow_rules': ['Ya, baik'],
      },
      operator: 'AND',
      conclusion: 'follow_rules_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengikuti aturan sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r129',
      name: 'follow_rules - follow_rules_cukup',
      antecedents: {
        'follow_rules': ['Ya, kadang perlu bantuan'],
      },
      operator: 'AND',
      conclusion: 'follow_rules_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengikuti aturan cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r130',
      name: 'follow_rules - follow_rules_kurang',
      antecedents: {
        'follow_rules': ['Sulit', 'Belum pernah'],
      },
      operator: 'AND',
      conclusion: 'follow_rules_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan mengikuti aturan kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r131',
      name: 'complex_questions - complex_questions_baik',
      antecedents: {
        'complex_questions': ['Ya, semua'],
      },
      operator: 'AND',
      conclusion: 'complex_questions_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menjawab pertanyaan kompleks sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r132',
      name: 'complex_questions - complex_questions_cukup',
      antecedents: {
        'complex_questions': ['Ya, sebagian'],
      },
      operator: 'AND',
      conclusion: 'complex_questions_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan menjawab pertanyaan kompleks cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r133',
      name: 'complex_questions - complex_questions_kurang',
      antecedents: {
        'complex_questions': ['Sedikit', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'complex_questions_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan menjawab pertanyaan kompleks kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r134',
      name: 'speech_comparison - speech_comparison_baik',
      antecedents: {
        'speech_comparison': ['Ya, lebih jelas'],
      },
      operator: 'AND',
      conclusion: 'speech_comparison_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kemampuan bicara dibandingkan sebaya sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r135',
      name: 'speech_comparison - speech_comparison_cukup',
      antecedents: {
        'speech_comparison': ['Serupa'],
      },
      operator: 'AND',
      conclusion: 'speech_comparison_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 0,
      recommendation: 'Kemampuan kemampuan bicara dibandingkan sebaya cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r136',
      name: 'speech_comparison - speech_comparison_kurang',
      antecedents: {
        'speech_comparison': ['Kurang jelas', 'Jauh berbeda'],
      },
      operator: 'AND',
      conclusion: 'speech_comparison_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'speech',
      severityImpact: 2,
      recommendation: 'Kemampuan kemampuan bicara dibandingkan sebaya kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'preschool_r137',
      name: 'express_feelings - express_feelings_baik',
      antecedents: {
        'express_feelings': ['Ya, dengan baik'],
      },
      operator: 'AND',
      conclusion: 'express_feelings_baik',
      confidence: 0.8,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengekspresikan perasaan sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'preschool_r138',
      name: 'express_feelings - express_feelings_cukup',
      antecedents: {
        'express_feelings': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'express_feelings_cukup',
      confidence: 0.7,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan mengekspresikan perasaan cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'preschool_r139',
      name: 'express_feelings - express_feelings_kurang',
      antecedents: {
        'express_feelings': ['Kadang-kadang', 'Belum'],
      },
      operator: 'AND',
      conclusion: 'express_feelings_kurang',
      confidence: 0.85,
      minAge: 56,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan mengekspresikan perasaan kurang, perlu perhatian khusus',
    ),
  ];

  // ============ UNIVERSAL RULES (SEMUA USIA) ============
  static final List<FCRuleModel> _universalRules = [
    const FCRuleModel(
      id: 'universal_r001',
      name: 'family_history - faktor_risiko_genetik',
      antecedents: {
        'family_history': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'faktor_risiko_genetik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 1,
      recommendation: 'Faktor genetik meningkatkan risiko speech delay',
    ),
    const FCRuleModel(
      id: 'universal_r002',
      name: 'family_history - tidak_ada_risiko_genetik',
      antecedents: {
        'family_history': ['Tidak', 'Tidak tahu'],
      },
      operator: 'AND',
      conclusion: 'tidak_ada_risiko_genetik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Tidak ada riwayat keluarga, indikator baik',
    ),
    const FCRuleModel(
      id: 'universal_r003',
      name: 'hearing_issues - respon_pendengaran_delayed',
      antecedents: {
        'hearing_issues': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'respon_pendengaran_delayed',
      confidence: 0.95,
      minAge: 0,
      maxAge: 999,
      category: 'response',
      severityImpact: 3,
      recommendation: 'Riwayat pendengaran - prioritas tinggi untuk evaluasi THT',
    ),
    const FCRuleModel(
      id: 'universal_r004',
      name: 'hearing_issues - pendengaran_normal',
      antecedents: {
        'hearing_issues': ['Tidak', 'Tidak yakin'],
      },
      operator: 'AND',
      conclusion: 'pendengaran_normal',
      confidence: 0.9,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Tidak ada indikasi masalah pendengaran',
    ),
    const FCRuleModel(
      id: 'universal_r005',
      name: 'parent_concern - perlu_monitoring',
      antecedents: {
        'parent_concern': ['Ya'],
      },
      operator: 'AND',
      conclusion: 'perlu_monitoring',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 1,
      recommendation: 'Kekhawatiran orang tua perlu diperhatikan',
    ),
    const FCRuleModel(
      id: 'universal_r006',
      name: 'parent_concern - pantau_ringan',
      antecedents: {
        'parent_concern': ['Tidak yakin'],
      },
      operator: 'AND',
      conclusion: 'pantau_ringan',
      confidence: 0.6,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Lakukan observasi perkembangan anak',
    ),
    const FCRuleModel(
      id: 'universal_r007',
      name: 'parent_concern - tidak_ada_kekhawatiran',
      antecedents: {
        'parent_concern': ['Tidak'],
      },
      operator: 'AND',
      conclusion: 'tidak_ada_kekhawatiran',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Orang tua merasa perkembangan anak sesuai',
    ),
    const FCRuleModel(
      id: 'universal_r008',
      name: 'eye_contact - eye_contact_baik',
      antecedents: {
        'eye_contact': ['Selalu'],
      },
      operator: 'AND',
      conclusion: 'eye_contact_baik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan eye_contact sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'universal_r009',
      name: 'eye_contact - eye_contact_cukup',
      antecedents: {
        'eye_contact': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'eye_contact_cukup',
      confidence: 0.7,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan eye_contact cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'universal_r010',
      name: 'eye_contact - eye_contact_kurang',
      antecedents: {
        'eye_contact': ['Jarang', 'Tidak pernah'],
      },
      operator: 'AND',
      conclusion: 'eye_contact_kurang',
      confidence: 0.85,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan eye_contact kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'universal_r011',
      name: 'pointing - pointing_baik',
      antecedents: {
        'pointing': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'pointing_baik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan pointing sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'universal_r012',
      name: 'pointing - pointing_cukup',
      antecedents: {
        'pointing': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'pointing_cukup',
      confidence: 0.7,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan pointing cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'universal_r013',
      name: 'pointing - pointing_kurang',
      antecedents: {
        'pointing': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'pointing_kurang',
      confidence: 0.85,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan pointing kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'universal_r014',
      name: 'social_smile - social_smile_baik',
      antecedents: {
        'social_smile': ['Sering'],
      },
      operator: 'AND',
      conclusion: 'social_smile_baik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan social_smile sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'universal_r015',
      name: 'social_smile - social_smile_cukup',
      antecedents: {
        'social_smile': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'social_smile_cukup',
      confidence: 0.7,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan social_smile cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'universal_r016',
      name: 'social_smile - social_smile_kurang',
      antecedents: {
        'social_smile': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'social_smile_kurang',
      confidence: 0.85,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan social_smile kurang, perlu perhatian khusus',
    ),
    const FCRuleModel(
      id: 'universal_r017',
      name: 'show_objects - show_objects_baik',
      antecedents: {
        'show_objects': ['Ya, sering'],
      },
      operator: 'AND',
      conclusion: 'show_objects_baik',
      confidence: 0.8,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan show_objects sangat baik dan sesuai usia',
    ),
    const FCRuleModel(
      id: 'universal_r018',
      name: 'show_objects - show_objects_cukup',
      antecedents: {
        'show_objects': ['Kadang-kadang'],
      },
      operator: 'AND',
      conclusion: 'show_objects_cukup',
      confidence: 0.7,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 0,
      recommendation: 'Kemampuan show_objects cukup, terus berikan stimulasi',
    ),
    const FCRuleModel(
      id: 'universal_r019',
      name: 'show_objects - show_objects_kurang',
      antecedents: {
        'show_objects': ['Jarang', 'Tidak'],
      },
      operator: 'AND',
      conclusion: 'show_objects_kurang',
      confidence: 0.85,
      minAge: 0,
      maxAge: 999,
      category: 'general',
      severityImpact: 2,
      recommendation: 'Kemampuan show_objects kurang, perlu perhatian khusus',
    ),
  ];

  /// Get rules for specific age
  static List<FCRuleModel> getRulesForAge(int ageInMonths) {
    return getAllRules()
        .where((rule) => rule.isApplicableForAge(ageInMonths))
        .toList();
  }
}